# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TableViewCellAddTimer' do
  pod 'ReactiveObjC', '~> 3.0.0'
  pod 'JSONModel', '~> 1.7.0'
  target 'TableViewCellAddTimerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TableViewCellAddTimerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
